services:
  - type: web
    name: bus_app.py3.0
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: "./start.sh"
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
